/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_Test */

#ifndef _Included_com_example_hellojni_Test
#define _Included_com_example_hellojni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_Test
 * Method:    Hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_Test_Hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
